#!/usr/bin/env python

# get a starting frequency and a population size 
# 	parameters for the function

# create a function to step through each generation

# make a list to store our allele frequncies 

# while loop
# while our loop allele frequency is between 0 and 1:
# 	draw a new allele frequency for next generation
#	by drawing from the binomial distribution 
# 	convert number of successes into a frequency

# Store our allele frequency into allele frequency list




# return  a list of the allele frequeny at each time point
# number of generations of fixation is the length of your list

import numpy as np 

frequency = 0.8
popsize = 1000

def wfmodel(pop, afreq):
	freq_list = []
	while afreq  < 1 and afreq > 0:
		success = np.random.binomial(2*pop, afreq)
		afreq = success / (2*pop)
		freq_list.append(afreq)
	return freq_list

print(wfmodel(popsize, frequency))
